"""auto vote

Revision ID: 277de8ab9b60
Revises: 560ed7afa402
Create Date: 2026-06-05 21:39:26.690584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277de8ab9b60'
down_revision: Union[str, Sequence[str], None] = '560ed7afa402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # op.add_column('posts', sa.Column('owner_id', sa.Integer(), nullable=False))
    # op.drop_constraint(op.f('post_users_fk'), 'posts', type_='foreignkey')
    # op.create_foreign_key(None, 'posts', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # op.drop_column('posts', 'Owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('posts', sa.Column('Owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # op.drop_constraint(None, 'posts', type_='foreignkey')
    # op.create_foreign_key(op.f('post_users_fk'), 'posts', 'users', ['Owner_id'], ['id'], ondelete='CASCADE')
    # op.drop_column('posts', 'owner_id')
    op.drop_table('votes')
    # ### end Alembic commands ###
